version: '3'

services:
  mq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: rabbit_mq
  reader:
    build:
      context: .
    container_name: rabbit_reader
    environment:
      MQ_HOST: mq
      MQ_PORT: 5672
      MQ_WR_QUEUE: ${MQ_WR_QUEUE}
      MQ_RD_QUEUE: ${MQ_RD_QUEUE}
      MQ_LOGIN: ${MQ_LOGIN}
      MQ_PASSWORD: ${MQ_PASSWORD}